const labels={nicht_geprueft:'Nicht geprüft',geprueft:'Geprüft',freigegeben:'Bereit zum Rendern',vorschau_erstellt:'Vorschau erstellt',veroeffentlicht:'Veröffentlicht',fehler:'Fehler'};
let products=[];let currentPlan=null;
const $=id=>document.getElementById(id);
const filters={search:$('search'),group:$('groupFilter'),status:$('statusFilter'),changed:$('changedOnly')};

async function loadInitial(){products=await fetch('data/products.json').then(r=>r.json());hydrate();render();}
function hydrate(){products=products.map(p=>({...p,selected:Boolean(p.selected),errors:Array.isArray(p.errors)?p.errors:[]}));fillSelect(filters.group,[...new Set(products.map(p=>p.productGroup))]);fillSelect(filters.status,[...new Set(products.map(p=>p.status))],v=>labels[v]||v);}
function fillSelect(select,values,label=x=>x){const value=select.value;select.innerHTML='<option value="">Alle</option>'+values.sort().map(v=>`<option value="${esc(v)}">${esc(label(v))}</option>`).join('');select.value=value;}
function visible(){const q=filters.search.value.trim().toLowerCase();return products.filter(p=>(!q||`${p.title} ${p.productKey}`.toLowerCase().includes(q))&&(!filters.group.value||p.productGroup===filters.group.value)&&(!filters.status.value||p.status===filters.status.value)&&(!filters.changed.checked||p.changed));}
function render(){const rows=visible();$('productRows').innerHTML=rows.map(row).join('');$('emptyState').hidden=rows.length>0;document.querySelectorAll('[data-select]').forEach(el=>el.addEventListener('change',e=>toggle(e.target.dataset.select,e.target.checked)));document.querySelectorAll('[data-detail]').forEach(el=>el.addEventListener('click',()=>showDetail(el.dataset.detail)));updateSummary(rows);}
function row(p){const check=p.errors.length?`<span class="error">${esc(p.errors.join(', '))}</span>`:'<span class="ok">Vollständig</span>';return `<tr><td><input type="checkbox" data-select="${esc(p.productKey)}" ${p.selected?'checked':''}></td><td><div class="productTitle">${esc(p.title)}</div><div class="productKey">${esc(p.productKey)}</div></td><td>${esc(p.productGroup)}</td><td><span class="badge status-${esc(p.status)}">${esc(labels[p.status]||p.status)}</span></td><td>${p.changed?'<span class="changed">Geändert</span>':'–'}</td><td>${check}</td><td>${esc(p.templateVersion||'–')}</td><td><button data-detail="${esc(p.productKey)}">Details</button></td></tr>`;}
function updateSummary(rows){const selected=products.filter(p=>p.selected);$('selectionCount').textContent=selected.length;$('createPlan').disabled=selected.length===0||selected.some(p=>p.errors.length);$('selectAll').checked=rows.length>0&&rows.every(p=>p.selected);const count=s=>products.filter(p=>p.status===s).length;$('stats').innerHTML=stat(products.length,'Produkte')+stat(products.filter(p=>p.changed).length,'Geändert')+stat(count('fehler'),'Fehler')+stat(products.filter(p=>p.selected).length,'Ausgewählt');}
function stat(n,t){return `<div class="stat"><strong>${n}</strong><span>${t}</span></div>`;}
function toggle(key,on){const p=products.find(x=>x.productKey===key);if(p)p.selected=on;render();}
function showDetail(key){const p=products.find(x=>x.productKey===key);$('detailContent').innerHTML=`<h2>${esc(p.title)}</h2><dl class="detailGrid"><dt>Product Key</dt><dd>${esc(p.productKey)}</dd><dt>Produktgruppe</dt><dd>${esc(p.productGroup)}</dd><dt>Status</dt><dd>${esc(labels[p.status]||p.status)}</dd><dt>Vorlage</dt><dd>${esc(p.templateVersion||'–')}</dd><dt>Source Hash</dt><dd>${esc(p.sourceHash||'–')}</dd><dt>Prüffehler</dt><dd>${p.errors.length?esc(p.errors.join(', ')):'Keine'}</dd><dt>PDF-Vorschau</dt><dd>${p.pdf?esc(p.pdf.split('/').pop()):'Nicht vorhanden'}</dd></dl>`;$('detailDialog').showModal();}
function makePlan(){const selected=products.filter(p=>p.selected);currentPlan={schemaVersion:1,createdAt:new Date().toISOString(),mode:'preview',publish:false,batchSize:10,source:'fsg-datenblatt-control-center',products:selected.map(({productKey,title,productGroup,templateVersion,sourceHash})=>({productKey,title,productGroup,templateVersion,sourceHash}))};$('planPreview').textContent=JSON.stringify(currentPlan,null,2);$('planDialog').showModal();}
function download(){const blob=new Blob([JSON.stringify(currentPlan,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`render-plan-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);}
function importReport(file){const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!Array.isArray(data))throw new Error('Report muss eine Liste sein');products=data.map(x=>({productKey:x.productKey,title:x.title,productGroup:x.productGroup||'unbekannt',status:x.errors?.length?'fehler':x.pdf?'vorschau_erstellt':x.changed?'freigegeben':'geprueft',selected:false,changed:Boolean(x.changed),errors:x.errors||[],pdf:x.pdf||null,sourceHash:x.sourceHash||null,templateVersion:x.templateVersion||null}));hydrate();render();}catch(e){alert(`Report konnte nicht geladen werden: ${e.message}`)}};reader.readAsText(file);}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
Object.values(filters).forEach(el=>el.addEventListener(el.type==='checkbox'?'change':'input',render));$('selectVisible').onclick=()=>{visible().filter(p=>!p.errors.length).forEach(p=>p.selected=true);render();};$('clearSelection').onclick=()=>{products.forEach(p=>p.selected=false);render();};$('selectAll').onchange=e=>{visible().filter(p=>!p.errors.length).forEach(p=>p.selected=e.target.checked);render();};$('createPlan').onclick=makePlan;$('downloadPlan').onclick=download;$('closeDialog').onclick=()=>$('detailDialog').close();$('closePlan').onclick=()=>$('planDialog').close();$('reportFile').onchange=e=>e.target.files[0]&&importReport(e.target.files[0]);loadInitial();